//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlchemoneyOverhaul.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlchemoneyOverhaul.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abecean Longfin,3
        ///Bear Claws,2
        ///Bee,6
        ///Beehive Husk,6
        ///Bleeding Crown,7
        ///Blisterwort,6
        ///Blue Butterfly Wing,6
        ///Blue Dartwing,3
        ///Blue Mountain Flower,4
        ///Bone Meal,3
        ///Briar Heart,4
        ///Butterfly Wing,6
        ///Canis Root,2
        ///Charred Skeever Hide,7
        ///Chaurus Eggs,5
        ///Chicken&apos;s Egg,1
        ///Creep Cluster,3
        ///Crimson Nimroot,10
        ///Cyrodilic Spadetail,6
        ///Daedra Heart,5
        ///Deathbell,3
        ///Dragon&apos;s Tongue,4
        ///Dwarven Oil,10
        ///Ectoplasm,0
        ///Elves Ear,1
        ///Eye of Sabre Cat,0
        ///Falmer Ear,0
        ///Fire Salts,3
        ///Fly Amanita,3
        ///Frost Mirriam,3
        ///Frost Salts, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ingredients {
            get {
                return ResourceManager.GetString("ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Abecean Longfin,Bear Claws,Hawk Feathers,Fortify One-Handed,Fortify Sneak,,,,236
        ///2,Abecean Longfin,Bear Claws,Pine Thrush Egg,Restore Stamina,Weakness to Poison,,,,76
        ///3,Abecean Longfin,Bear Claws,Powdered Mammoth Tusk,Restore Stamina,Fortify Sneak,,,,143
        ///4,Abecean Longfin,Bear Claws,Purple Mountain Flower,Restore Stamina,Fortify Sneak,,,,143
        ///5,Abecean Longfin,Bear Claws,Sabre Cat Tooth,Restore Stamina,Weakness to Poison,,,,76
        ///6,Abecean Longfin,Bear Claws,Small Pearl,Restore Stamina,Fortify One-Handed [rest of string was truncated]&quot;;.
        /// </summary>
        public static string skyrimPotions {
            get {
                return ResourceManager.GetString("skyrimPotions", resourceCulture);
            }
        }
    }
}
